radio_points = {'Радио Europa+': 'http://ep128.hostingradio.ru:8030/ep128', 
                'Дорожное радио': 'http://dor2server.streamr.ru:8000/dor_64_no',
                'Радио Шансон': 'http://chanson.hostingradio.ru:8041/chanson-sochi192.mp3',
                'Радио Record': 'http://radio-srv1.11one.ru/record192k.mp3', 
                'Радио Зайцев метал': 'https://zaycevfm.cdnvideo.ru/ZaycevFM_metal_256.mp3',
                'Классическая музыка': ' http://stream.srg-ssr.ch/m/rsc_de/mp3_128',
		'Hype FM': 'http://54.154.49.88:8000/HipHop/HypeFM',
                'Ordinary Ambient': 'http://galnet.ru:8000/soft', 
                'Premium': 'http://listen.rpfm.ru:9000/premium128',
                'Dance': 'http://stream.nonstopplay.co.uk/nsp-128k-mp3',
                'Fallout FM': 'http://fallout.fm:8000/falloutfm1.ogg',
                'Руки Вверх!': 'https://radiorecord.hostingradio.ru/rv96.aacp',
                '2x2': 'http://95.104.192.220:8001/radio2x2.ogg',
                'Детское радио': 'http://ic7.101.ru:8000/v14_1'}
